//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostType
    {
        public PostType()
        {
            this.Staffs = new HashSet<Staff>();
            this.VacationTypes = new HashSet<VacationType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PostTypesDayTimeCoefficientId { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<VacationType> VacationTypes { get; set; }
        public virtual PostTypesDayTimeCoefficient PostTypesDayTimeCoefficient { get; set; }
    }
}
