//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTypesDayTimeCoefficientValue
    {
        public int Id { get; set; }
        public int PostTypesDayTimeCoefficientId { get; set; }
        public int GendersId { get; set; }
        public double Coefficient { get; set; }
        public double TimeNormOfDay { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual PostTypesDayTimeCoefficient PostTypesDayTimeCoefficient { get; set; }
    }
}
