//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTypesDayTimeCoefficient
    {
        public PostTypesDayTimeCoefficient()
        {
            this.PostTypesDayTimeCoefficientValues = new HashSet<PostTypesDayTimeCoefficientValue>();
            this.PostTypes = new HashSet<PostType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PostTypesDayTimeCoefficientValue> PostTypesDayTimeCoefficientValues { get; set; }
        public virtual ICollection<PostType> PostTypes { get; set; }
    }
}
