//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegNorm
    {
        public RegNorm()
        {
            this.Staffs = new HashSet<Staff>();
            this.TimeNormOfMonths = new HashSet<TimeNormOfMonth>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Norm { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<TimeNormOfMonth> TimeNormOfMonths { get; set; }
    }
}
