//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Vacations = new HashSet<Vacation>();
        }
    
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string PatronymicName { get; set; }
        public short TabelNumber { get; set; }
        public int PostId { get; set; }
        public int PostTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int RegNormId { get; set; }
        public int GenderId { get; set; }
        public int RegNormGraphTypeId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual PostType PostType { get; set; }
        public virtual RegNorm RegNorm { get; set; }
        public virtual ICollection<Vacation> Vacations { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual RegNormGraphType RegNormGraphType { get; set; }
    }
}
