//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationType
    {
        public VacationType()
        {
            this.Vacations = new HashSet<Vacation>();
            this.PostTypes = new HashSet<PostType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Vacation> Vacations { get; set; }
        public virtual ICollection<PostType> PostTypes { get; set; }
    }
}
